model:
  name: "H2-valle-2023-2043"
  timeseries_data_path: data
  time:
    resolution: 1h
  subset_time: ['2028-01-01 00:00', '2029-12-31 23:00']

run:
  solver: cbc
  objective_options:
    cost_class: {monetary: 1, co2: 0}
  ensure_feasibility: true 

import:
  - locations.yml
  - techs.yml
  - links.yml